spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      jakarta:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_udemy?useTimezone=true&serverTimezone=UTC
    username: root
    password: adm123